select 
    d.DEPARTMENT_NAME AS DEPARTMENT_NAME,
    first_name || ' ' || last_name AS EMP_NAME,
    SALARY AS MAX_SALARY 
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS d USING(DEPARTMENT_ID)
WHERE (DEPARTMENT_ID,SALARY) IN (
    select DEPARTMENT_ID, max(salary) 
    from EMPLOYEES 
    group by DEPARTMENT_ID
);